[package]
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
name = "dupfinder"
version = "0.1.0"

[dependencies]
argparse = "0.2.1"
clippy = "*"
image = "0.7.0"
pbr = "0.0.4"
rayon = "*"
rust-crypto = "0.2.34"
serde = "*"
serde_json = "*"

[dependencies.img_hash]
features = ["rust-image"]
git = "https://github.com/cybergeek94/img_hash"
