[package]
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
name = "dupfinder"
version = "0.1.0"

[dependencies]
argparse = "0.2"
image = "0.14"
rayon = "0.8"
serde = "1"
serde_json = "1"
murmurhash3 = "*"
crossbeam = "0.2"
walkdir = "1"

[dependencies.img_hash]
features = ["rust-image"]
git = "https://github.com/GyrosOfWar/img_hash"
