[package]
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
name = "dupfinder"
version = "0.1.0"

[dependencies]
argparse = "*"
image = "*"
rayon = "*"
serde = "*"
serde_json = "*"
murmurhash3 = "*"
crossbeam = "*"
walkdir = "*"

[dependencies.img_hash]
features = ["rust-image"]
git = "https://github.com/cybergeek94/img_hash"
