[package]
name = "dupfinder"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[dependencies]
pbr = "0.0.4"
argparse = "0.2.1"
rust-crypto = "0.2.34"
image = "0.5.4"

[dependencies.img_hash]
git = "https://github.com/cybergeek94/img_hash"
features = ["rust-image"]
