[package]
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
name = "dupfinder"
version = "0.1.0"

[dependencies]
argparse = "0.2"
crossbeam = "0.2"
failure = "0.1.1"
image = "0.14"
murmurhash3 = "*"
parking_lot = "0.5.3"
rayon = "0.8"
serde = "1"
serde_json = "1"
structopt = "0.1.6"
structopt-derive = "0.1.6"
walkdir = "1"

[dependencies.img_hash]
features = ["rust-image"]
git = "https://github.com/GyrosOfWar/img_hash"
